version: '2'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    links:
      - db
  db:
    build: ./db
#  flask-restplus-boilerplate:
#    build: ./flask-restplus-boilerplatee
#    ports:
#      - "5000:5000"
#  blogyourlife:
#    build: ./blogyourlife
#    ports:
#      - "5000:5000"




